// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserListApp.Infrastructure.Persistance;

#nullable disable

namespace UserListApp.Infrastructure.Migrations
{
    [DbContext(typeof(UserListAppContext))]
    [Migration("20240817184125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserListApp.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Name = "Alice",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Name = "Bob",
                            PhoneNumber = "234-567-8901"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            Name = "Charlie",
                            PhoneNumber = "345-678-9012"
                        },
                        new
                        {
                            Id = 4,
                            Email = "david@example.com",
                            Name = "David",
                            PhoneNumber = "456-789-0123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "eva@example.com",
                            Name = "Eva",
                            PhoneNumber = "567-890-1234"
                        },
                        new
                        {
                            Id = 6,
                            Email = "frank@example.com",
                            Name = "Frank",
                            PhoneNumber = "678-901-2345"
                        },
                        new
                        {
                            Id = 7,
                            Email = "grace@example.com",
                            Name = "Grace",
                            PhoneNumber = "789-012-3456"
                        },
                        new
                        {
                            Id = 8,
                            Email = "hank@example.com",
                            Name = "Hank",
                            PhoneNumber = "890-123-4567"
                        },
                        new
                        {
                            Id = 9,
                            Email = "ivy@example.com",
                            Name = "Ivy",
                            PhoneNumber = "901-234-5678"
                        },
                        new
                        {
                            Id = 10,
                            Email = "jack@example.com",
                            Name = "Jack",
                            PhoneNumber = "012-345-6789"
                        },
                        new
                        {
                            Id = 11,
                            Email = "kara@example.com",
                            Name = "Kara",
                            PhoneNumber = "123-456-7891"
                        },
                        new
                        {
                            Id = 12,
                            Email = "leo@example.com",
                            Name = "Leo",
                            PhoneNumber = "234-567-8902"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
